version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5442:5432"
    environment:
      POSTGRES_PASSWORD: sspw
      POSTGRES_DB: dbcmp_test
      POSTGRES_USER: pguser
  mysql:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3316:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: dbcmp_test
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: sspw
      MYSQL_ROOT_PASSWORD: sspw
